Declarative schema y columnas de invoice y creditmemo
holamugar/module-customer-identification-document pull request #24
Opened 2020-11-10 19:25 UTC by manuelcanepa

### Descripción

Instalación utilizando declarative schema. Agregado de columnas en invoice y creditmemo.

### Issues relacionados (si fuera aplicable)
1. holamugar/module-customer-identification-document#12: Convertir setup scripts a configuración de declarative schema
2. holamugar/module-customer-identification-document#9: Faltan los campos para invoice y creditmemo

2020-11-10 20:24 UTC, barbanet requested changes

2020-11-10 20:24 UTC, barbanet commented on etc/db_schema_whitelist.json
> +}
¿Agregamos nueva línea al final del archivo?

2020-11-10 20:24 UTC, barbanet commented on etc/db_schema.xml
> +<?xml version="1.0"?>
Falta el copyright y datos de licencia.

2020-11-10 20:25 UTC, barbanet commented
@manuelcanepa  ¿Se había definido agregar campos a la tabla en lugar de Extension Attributes?

2020-11-10 20:32 UTC, manuelcanepa commented
@barbanet Los campos ya se agregan, solo que por InstallData en lugar de declarative schema. Si se define que hay que cambiar esa logica, entonces desestimar este PR.

2020-11-10 20:32 UTC, manuelcanepa commented
... y cerrar el ticket correspondiente.

2020-11-11 02:33 UTC, manuelcanepa commented on etc/db_schema_whitelist.json
> +}
Corregido

2020-11-11 02:33 UTC, manuelcanepa commented on etc/db_schema.xml
> +<?xml version="1.0"?>
Corregido

2020-11-11 03:17 UTC, barbanet approved these changes

2020-11-11 03:57 UTC, merged